---
- name: Disable password authentication via SSH
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: ^PasswordAuthentication
    line: PasswordAuthentication no

- name: Disable root login via SSH
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: ^PermitRootLogin
    line: PermitRootLogin no

- name: Ensure SSH service is restarted
  ansible.builtin.service:
    name: ssh
    state: restarted
