---
- name: Download Docker GPG key using command
  ansible.builtin.shell: |
    curl -fsSL https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  args:
    creates: /usr/share/keyrings/docker-archive-keyring.gpg

- name: Get system architecture
  ansible.builtin.command: dpkg --print-architecture
  register: arch_output

- name: Get distribution codename
  ansible.builtin.command: lsb_release -cs
  register: codename_output

- name: Add Docker APT repository
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/docker.list
    line: "deb [arch={{ arch_output.stdout }} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ codename_output.stdout }} stable"
    create: true

- name: Update apt packages to include Docker
  ansible.builtin.apt:
    update_cache: true

- name: Install Docker
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Ensure Docker is started and enabled
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started

- name: Add kamal user to docker group
  ansible.builtin.user:
    name: kamal
    groups: docker
    append: true

- name: Ensure Docker is started and enabled
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started

- name: Restart Docker to apply changes
  ansible.builtin.systemd:
    name: docker
    state: restarted
    enabled: true

# TODO: add robust config options such as custom data root, config.json, etc
