---
- name: Update apt packages
  ansible.builtin.apt:
    update_cache: true

- name: Install required system packages for docker deploy
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - software-properties-common
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release

- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker apt repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
    state: present

- name: Install Docker
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Ensure Docker is started and enabled
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started

- name: Add config user to docker group
  ansible.builtin.user:
    name: config
    groups: docker
    append: true

- name: Ensure Docker is started and enabled
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started

- name: Install Docker SDK for Python via apt
  ansible.builtin.apt:
    name: python3-docker
    state: present

- name: Restart Docker to apply changes
  ansible.builtin.systemd:
    name: docker
    state: restarted
    enabled: true

# TODO: add robust config options such as custom data root, config.json, etc
# TODO: add config option for docker compose install
