---
- name: Install UFW
  ansible.builtin.apt:
    name: ufw
    state: present
    update_cache: true

- name: Set default policy for incoming traffic
  community.general.ufw:
    default: deny
    direction: incoming
    state: enabled
    logging: true

- name: Set default policy for outgoing traffic
  community.general.ufw:
    default: deny
    direction: outgoing
    state: enabled
    logging: true

- name: Allow inbound traffic for specified TCP ports
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
    direction: in
  loop: "{{ allowed_inbound_tcp_ports | default([22, 80, 443]) }}"

- name: Allow outbound traffic for specified TCP ports
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
    direction: out
  loop: "{{ allowed_outbound_tcp_ports | default([80, 443]) }}"

- name: Allow outbound traffic for specified UDP ports
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: udp
    direction: out
  loop: "{{ allowed_outbound_udp_ports | default([53, 123]) }}"

- name: Allow specified inbound UDP ports if defined
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: udp
    direction: in
  loop: "{{ allowed_inbound_udp_ports | default([]) }}"
  when: allowed_inbound_udp_ports is defined and allowed_inbound_udp_ports | length > 0
