---
- name: Install unattended-upgrades
  ansible.builtin.apt:
    name: unattended-upgrades
    state: present
    update_cache: true

- name: Configure unattended-upgrades
  ansible.builtin.copy:
    src: ./templates/unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: "0644"

- name: Enable automatic upgrades
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/20auto-upgrades
    line: APT::Periodic::Unattended-Upgrade "1";
    create: true
    owner: root
    group: root
    mode: "0644"

- name: Install fail2ban
  ansible.builtin.apt:
    name: fail2ban
    state: present
    update_cache: true

- name: Configure fail2ban
  ansible.builtin.template:
    src: ./templates/jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: "0644"

- name: Ensure fail2ban is running and enabled
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true

- name: Ensure systemd-timesyncd is installed
  ansible.builtin.apt:
    name: systemd-timesyncd
    state: present
    update_cache: true

- name: Enable and start systemd-timesyncd
  ansible.builtin.systemd:
    name: systemd-timesyncd
    state: started
    enabled: true

- name: Check NTP status
  ansible.builtin.command: timedatectl status
  register: ntp_status
  changed_when: false

- name: Install auditd
  ansible.builtin.apt:
    name: auditd
    state: present
    update_cache: true

- name: Ensure auditd is running and enabled
  ansible.builtin.service:
    name: auditd
    state: started
    enabled: true

- name: Install logrotate
  ansible.builtin.package:
    name: logrotate
    state: present

- name: Configure logrotate with defaults
  ansible.builtin.template:
    src: logrotate.conf.j2
    dest: /etc/logrotate.conf
    owner: root
    group: root
    mode: "0644"

- name: Configure log rotation for system logs
  ansible.builtin.copy:
    dest: /etc/logrotate.d/syslog
    content: |
      /var/log/syslog {
          weekly
          rotate 4
          compress
          missingok
          notifempty
          create 0640 root adm
      }
    owner: root
    group: root
    mode: "0644"

# TODO: Rework this file as a series of tasks, with environment variable overrides to install them
# TODO: Seperate logging in to its own file, and configure logwatch and SMTP if desired
